version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5433/${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: 'postgres'
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  dev:
    build: .
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5433/${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - postgres